# ----------------------------------------------------------
# GitHub Actions Workflow: Terraform Apply & Output Summary
# ----------------------------------------------------------
# This workflow:
# - Configures AWS credentials using OIDC
# - Checks out the repository
# - Writes the MCD API key file for Cisco integration
# - Sets up Terraform (version 1.7.5)
# - Updates the S3 backend bucket name in provider.tf
# - Runs Terraform init, validate, plan, and apply
# - Prints Terraform outputs to the log
# - Saves Terraform outputs to tf_outputs.txt for download
# - Adds Terraform outputs to the GitHub Actions job summary for easy access
#
# Notes:
# - Outputs are available in the Actions log, tf_outputs.txt, and the job summary UI
# - Use these outputs to fill in your test summary and for troubleshooting
# ----------------------------------------------------------

name: Terraform Apply

permissions:
  id-token: write
  contents: read

on:
  # Enable manual workflow trigger
  workflow_dispatch:

  # Enable automatic run on push to any branch
  push:
    branches:
      - main
      - pilot
  
jobs:
  terraform_apply:
    name: Terraform Apply
    runs-on: ubuntu-22.04

    steps:
      - name: Configure aws credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_OIDC_IDP_ROLE_ARN }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Write MCD API Key File
        working-directory: terraform
        run: echo '${{ secrets.MCD_API_KEY }}' > cisco_mcd/mcd_api_key.json

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.7.5

      - name: Update Terraform S3 backend bucket name
        working-directory: terraform
        run: sed -i 's/PLACEHOLDER/${{ secrets.AWS_S3_BUCKET_NAME }}/' provider.tf 

      - name: Terraform init
        working-directory: terraform
        run: terraform init

      - name: Terraform Validate
        working-directory: terraform
        run: terraform validate

      - name: Terraform Plan
        working-directory: terraform
        run: terraform plan

      - name: Terraform Apply
        working-directory: terraform
        run: terraform apply -auto-approve

      - name: Terraform Output (print to log)
        working-directory: terraform
        run: terraform output

      - name: Save Terraform Outputs to File
        working-directory: terraform
        run: terraform output > tf_outputs.txt

      - name: Add Terraform Outputs to Job Summary
        working-directory: terraform
        run: |
          echo '### Terraform Outputs' >> $GITHUB_STEP_SUMMARY
          terraform output >> $GITHUB_STEP_SUMMARY

      - name: Upload Terraform Outputs File
        uses: actions/upload-artifact@v3
        with:
          name: tf_outputs
          path: terraform/tf_outputs.txt


