name: Terraform Apply

env:
  AWS_REGION: us-east-1

permissions:
  id-token: write
  contents: read

on:
  workflow_dispatch:
  # push:
  #   branches:
  #     - main

jobs:
  terraform_apply:
    name: Terraform Apply
    runs-on: ubuntu-latest

    steps:
      - name: Configure aws credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::257344898502:role/GitHubAction-AssumeRoleWithAction
          aws-region: ${{ env.AWS_REGION }}

      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Write MCD API Key File
        working-directory: terraform
        run: echo '${{ secrets.MCD_API_KEY }}' > cisco_mcd/mcd_api_key.json

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.6.6

      - name: Terraform init
        working-directory: terraform
        run: terraform init

      - name: Terraform Validate
        working-directory: terraform
        run: terraform validate

      - name: Terraform Plan
        working-directory: terraform
        run: terraform plan

      - name: Terraform Apply
        working-directory: terraform
        run: terraform apply -auto-approve
