name: Terraform Apply

on:
  push:
    branches:
      - main

jobs:
  terraform_apply:
    name: Terraform Apply
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID:  ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY:  ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: 'us-east-1'

    steps:

    - name: Checkout Repo
      uses: actions/checkout@v4

    - name: Write MCD API Key File
      run: echo $MCD_API_KEY > mcd_api_key.json

    - name: Terraform Install
      run: sudo apt install -y terraform

    - name: Terraform Validate
      working-directory: ./terraform
      run: terraform validate

    - name: Terraform Apply
      working-directory: ./terraform
      run: terraform apply
