name: Terraform Apply

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_REGION: ${{ secrets.AWS_REGION }}

on:
  workflow_dispatch:
  # push:
  #   branches:
  #     - main

jobs:
  terraform_apply:
    name: Terraform Apply
    runs-on: ubuntu-latest

    steps:
      - uses: hashicorp/setup-terraform@v2

      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Write MCD API Key File
        working-directory: ./terraform
        run: echo $MCD_API_KEY > mcd_api_key.json

      - name: Terraform init
        working-directory: ./terraform
        run: terraform init

      - name: Terraform Validate
        working-directory: ./terraform
        run: terraform validate

      - name: Terraform Apply
        working-directory: ./terraform
        run: terraform apply
